local Policy=dofile(arg[1])
local state=Policy.new(0, 1)
local a,b,c={},{},{}
assert(not Policy.accept_contact(state,a,0,'heavy',1), 'initial heavy was free')
assert(Policy.accept_contact(state,a,0,'light',.5))
assert(not Policy.accept_contact(state,a,.1,'light',.5), 'waggle bypassed target cooldown')
assert(Policy.accept_contact(state,b,.1,'light',.5), 'introduced global cooldown/cleave cap')
assert(not Policy.accept_contact(state,a,.499,'light',.5))
assert(Policy.accept_contact(state,a,.5,'light',.5), 'stationary overlap did not become eligible')
assert(not Policy.accept_contact(state,a,.5,'light',.5), 'duplicate hurtbox/substep hit twice')
assert(Policy.accept_contact(state,a,1,'heavy',1))
assert(Policy.accept_contact(state,b,1,'heavy',1), 'heavy imposed global cooldown')
assert(not Policy.accept_contact(state,a,1.1,'light',.5), 'mode switch erased heavy cooldown')
assert(Policy.accept_contact(state,c,1.1,'heavy',1), 'new target started a fresh initial charge delay')
assert(Policy.accept_contact(state,a,2,'heavy',1), 'continuous heavy contact failed after target deadline')
Policy.begin_heavy_charge(state,2,1)
assert(not Policy.accept_contact(state,a,2.1,'light',.5), 'recharge erased target history')
assert(not Policy.accept_contact(state,{},2.1,'heavy',1))
assert(Policy.accept_contact(state,{},100,'heavy',1))
local d={}
assert(Policy.accept_contact(state,d,100,'heavy',1))
assert(not Policy.accept_contact(state,d,100,'heavy',1), 'idle time banked a burst')
assert(not Policy.accept_contact(state,d,0/0,'light',.5))
assert(not Policy.accept_contact(state,nil,101,'light',.5))
assert(not Policy.accept_contact(state,d,101,'light',0))
Policy.forget_target(state,d)
assert(state.next_hit[d]==nil)
print('continuous per-target light/heavy cooldowns, unlimited targets, no initial/banked heavy passed')
