local Wrist=dofile(assert(arg[1]))
-- Bars.
local bars=Wrist.bars({health=150,max_health=200,toughness=.5,stamina=1})
assert(#bars==3 and bars[1].id=='health' and math.abs(bars[1].fraction-.75)<1e-9 and bars[1].text=='150')
assert(bars[2].id=='toughness' and bars[2].fraction==.5 and bars[3].id=='stamina')
bars=Wrist.bars({health=250,max_health=200,toughness=1.5,stamina=-1})
assert(bars[1].fraction==1 and bars[2].fraction==1 and bars[3].fraction==0,'clamped')
assert(#Wrist.bars({toughness=.3})==1,'missing values skipped')
assert(#Wrist.bars({health=10,max_health=0})==0,'zero max health')
assert(#Wrist.bars(nil)==0)
-- Colours: health white, toughness the HUD's toughness blue.
local c=Wrist.bars({health=1,max_health=2,toughness=.5,stamina=.5})
assert(c[1].color==Wrist.HEALTH_COLOR and c[1].color[1]==255 and c[1].color[2]==255 and c[1].color[3]==255)
assert(c[2].color[1]==108 and c[2].color[2]==187 and c[2].color[3]==196)
assert(Wrist.visible==nil,'always shown: no facing gate')
print('wrist_display=pass bars clamp missing colours always_shown')
