local Mirror=dofile(assert(arg[1]))
assert(Mirror.keeps_slot('slot_body_torso',{slot_type='body'}))
assert(Mirror.keeps_slot('slot_gear_head',{slot_type='gear'}))
assert(Mirror.keeps_slot('slot_gear_material_override_decal',{slot_type='material'}))
assert(Mirror.keeps_slot('slot_unarmed',{slot_type='weapon'}),'spawner plumbing')
assert(not Mirror.keeps_slot('slot_primary',{slot_type='weapon'}),'no weapons')
assert(not Mirror.keeps_slot('slot_pocketable',{slot_type='gadget',ignore_character_spawning=true}))
assert(not Mirror.keeps_slot('slot_companion_gear_full',{slot_type='gear'}),'no companion')
assert(not Mirror.keeps_slot('slot_insignia',{slot_type='ui',ignore_character_spawning=true}))
local a={j_hips=2,j_head=9}
local b={j_hips=2,j_head=9}
local c={j_hips=2,j_head=10}
local function lookup(t) return function(name) return t[name] end end
assert(Mirror.same_layout(246,246,lookup(a),lookup(b),{'j_hips','j_head'}))
assert(not Mirror.same_layout(246,220,lookup(a),lookup(b),{'j_hips'}),'node counts differ')
assert(not Mirror.same_layout(246,246,lookup(a),lookup(c),{'j_hips','j_head'}),'probe index differs')
assert(Mirror.parse_mode('mirror')=='mirror' and Mirror.parse_mode(' overlay\n')=='overlay')
assert(Mirror.parse_mode('enabled')==nil and Mirror.parse_mode(nil)==nil)
assert(Mirror.MODES.overlay.distance==0 and not Mirror.MODES.overlay.facing)
assert(Mirror.MODES.mirror.distance==Mirror.MIRROR_DISTANCE and Mirror.MODES.mirror.facing)
local head={slot_gear_head=true,slot_body_hair=true}
assert(Mirror.hides_slot('overlay','slot_gear_head',head))
assert(not Mirror.hides_slot('overlay','slot_body_torso',head))
assert(not Mirror.hides_slot('mirror','slot_gear_head',head),'mirror shows the whole character')
assert(not Mirror.hides_slot(nil,'slot_gear_head',head))
assert(Mirror.parse_mode('overlaycopy')=='overlaycopy')
assert(Mirror.MODES.overlay.solve_arms and not Mirror.MODES.overlaycopy.solve_arms)
assert(Mirror.MODES.overlaycopy.distance==0 and Mirror.hides_slot('overlaycopy','slot_gear_head',head))
local function near(a,b,e) return math.abs(a-b)<(e or 1e-6) end
local function dist(a,b) return math.sqrt((a[1]-b[1])^2+(a[2]-b[2])^2+(a[3]-b[3])^2) end
local o={0,0,0}
local e,h,ok=Mirror.elbow(o,{0.2,0,-1},{0.4,0,0},0.3,0.3)
assert(ok and near(dist(o,e),0.3) and near(dist(e,h),0.3) and near(dist(h,{0.4,0,0}),0),'reachable: lengths kept, hand on target')
assert(near(e[1],0.2) and e[3]<0 and near(e[2],0),'bends toward the hint')
e,h,ok=Mirror.elbow(o,{0.2,0,1},{0.4,0,0},0.3,0.3)
assert(e[3]>0,'hint above bends up')
e,h,ok=Mirror.elbow(o,{0.2,0,-1},{1,0,0},0.3,0.3)
assert(not ok and near(dist(o,h),0.5994,1e-4) and near(dist(o,e),0.3) and near(dist(e,h),0.3,1e-4),'out of reach: straight toward target, lengths kept')
e,h,ok=Mirror.elbow(o,{0.1,0,0},{0.4,0,0},0.3,0.3)
assert(ok and e[3]<0,'hint on the line bends down')
e,h,ok=Mirror.elbow(o,{0,0,0.1},{0,0,0.4},0.3,0.3)
assert(ok and near(dist(o,e),0.3) and near(dist(e,h),0.3),'vertical reach with hint on the line')
e,h,ok=Mirror.elbow(o,{0,0,-1},{0.05,0,0},0.3,0.2)
assert(not ok and near(dist(o,e),0.3) and near(dist(e,h),0.2,1e-3),'too close: lengths kept')
assert(Mirror.elbow(o,o,o,0.3,0.3)==nil and Mirror.elbow(o,o,{1,0,0},0,0.3)==nil)
print('body_mirror=pass keeps_slot same_layout modes hides_slot elbow')
