local Wrist=dofile(assert(arg[1]))
-- Visibility: facing the eye, within reach, with hysteresis.
assert(Wrist.visible(false,{1,0,0},{1,0,0},.4),'facing the eye shows')
assert(not Wrist.visible(false,{1,0,0},{0.7,0.714,0},.4),'0.7 facing does not show')
assert(Wrist.visible(true,{1,0,0},{0.7,0.714,0},.4),'0.7 facing keeps it shown')
assert(not Wrist.visible(true,{1,0,0},{0.5,0.866,0},.4),'0.5 facing hides')
assert(not Wrist.visible(false,{1,0,0},{1,0,0},.9),'too far')
assert(not Wrist.visible(false,{1,0,0},{-1,0,0},.3),'back of the wrist away')
assert(not Wrist.visible(false,nil,{1,0,0},.3) and not Wrist.visible(false,{1,0,0},{1,0,0},0/0))
-- Bars.
local bars=Wrist.bars({health=150,max_health=200,toughness=.5,stamina=1})
assert(#bars==3 and bars[1].id=='health' and math.abs(bars[1].fraction-.75)<1e-9 and bars[1].text=='150')
assert(bars[2].id=='toughness' and bars[2].fraction==.5 and bars[3].id=='stamina')
bars=Wrist.bars({health=250,max_health=200,toughness=1.5,stamina=-1})
assert(bars[1].fraction==1 and bars[2].fraction==1 and bars[3].fraction==0,'clamped')
assert(#Wrist.bars({toughness=.3})==1,'missing values skipped')
assert(#Wrist.bars({health=10,max_health=0})==0,'zero max health')
assert(#Wrist.bars(nil)==0)
print('wrist_display=pass visibility hysteresis reach bars clamp missing')
