return {
    vr_menu_back = {en = "B / Menu"},
    vr_menu_point_select = {en = "Point + RT"},
    vr_turning = {en = "VR turning"},
    vr_turning_description = {en = "Turn with the right stick horizontally. Centre it after menus, tracking loss or changing modes. Keyboard and mouse controls remain available."},
    vr_turn_mode = {en = "Turning mode"},
    vr_turn_mode_description = {en = "Smooth turning is the default. Snap turns once per stick deflection. Turn this off to use left/right stick shortcuts instead."},
    vr_turn_smooth = {en = "Smooth"},
    vr_turn_snap45 = {en = "Snap 45 degrees"},
    vr_turn_snap90 = {en = "Snap 90 degrees"},
    vr_turn_off = {en = "Off (allow horizontal shortcuts)"},
    vr_turn_speed = {en = "Smooth speed (degrees per second)"},
    vr_turn_speed_description = {en = "Speed at full right-stick deflection. Partial deflection turns more slowly. Only applies to smooth turning."},
    vr_prompt_right_trigger = {en = "RT"},
    vr_prompt_left_trigger = {en = "LT"},
    vr_prompt_right_grip = {en = "R Grip"},
    vr_prompt_left_grip = {en = "L Grip"},
    vr_prompt_x = {en = "X"},
    vr_prompt_y = {en = "Y"},
    vr_prompt_a = {en = "A"},
    vr_prompt_b = {en = "B"},
    vr_prompt_l3 = {en = "L3"},
    vr_prompt_r3 = {en = "R3"},
    vr_prompt_menu = {en = "Menu"},
    vr_prompt_right_stick_up = {en = "RS Up"},
    vr_prompt_right_stick_down = {en = "RS Down"},
    vr_prompt_right_stick_left = {en = "RS Left"},
    vr_prompt_right_stick_right = {en = "RS Right"},
    vr_prompt_switch = {en = "switch"},
    controller_bindings = {en = "Gameplay controller bindings"},
    controller_bindings_description = {en = "Gameplay only; menu select, back and scrolling keep their standard controls. Release buttons and centre the stick after changing a binding. Multiple controls may share an action. Stick diagonals can activate two shortcuts together. Aim hands stay unchanged. Reset settings to restore the original layout."},
    vr_bind_right_trigger = {en = "Right trigger"},
    vr_bind_left_trigger = {en = "Left trigger"},
    vr_bind_right_grip = {en = "Right grip"},
    vr_bind_left_grip = {en = "Left grip"},
    vr_bind_x = {en = "X (left primary button)"},
    vr_bind_y = {en = "Y (left secondary button)"},
    vr_bind_a = {en = "A (right primary button)"},
    vr_bind_b = {en = "B (right secondary button)"},
    vr_bind_l3 = {en = "L3 (left stick click)"},
    vr_bind_r3 = {en = "R3 (right stick click)"},
    vr_bind_menu = {en = "Left menu button"},
    vr_bind_right_stick_up = {en = "Right stick up"},
    vr_bind_right_stick_down = {en = "Right stick down"},
    vr_bind_right_stick_left = {en = "Right stick left (turning off)"},
    vr_bind_right_stick_right = {en = "Right stick right (turning off)"},
    vr_action_unbound = {en = "Unbound"},
    vr_action_primary = {en = "Primary attack / fire"},
    vr_action_alternate = {en = "Aim / block / alternate attack"},
    vr_action_special = {en = "Weapon special"},
    vr_action_interact = {en = "Interact"},
    vr_action_reload = {en = "Reload"},
    vr_action_interact_reload = {en = "Interact + reload (original)"},
    vr_action_quick_wield = {en = "Switch weapon"},
    vr_action_jump = {en = "Jump"},
    vr_action_dodge = {en = "Dodge"},
    vr_action_jump_dodge = {en = "Jump + dodge (original)"},
    vr_action_crouch = {en = "Crouch"},
    vr_action_sprint = {en = "Sprint"},
    vr_action_tag = {en = "Tag target"},
    vr_action_blitz = {en = "Blitz / grenade"},
    vr_action_combat_ability = {en = "Combat ability"},
    vr_action_inspect = {en = "Inspect weapon"},
    vr_action_menu = {en = "Open pause menu"},
    hud_editor = {en = "HUD layout editor"},
    hud_editor_button = {en = "Toggle editor"},
    hud_editor_description = {en = "Requires the separate Custom HUD mod. Select this, then close the menus to edit in the desktop view. Select again before closing to cancel."},
    hud_editor_dependency = {en = "Install and enable Custom HUD to edit the HUD layout."},
    hud_editor_gameplay = {en = "Enter gameplay with the VR HUD enabled before opening its layout editor."},
    hud_editor_close_menu = {en = "Close the menus to toggle HUD layout editing in the desktop view."},
    hud_editor_cancelled = {en = "HUD layout editor request cancelled."},
    hud_editor_notice = {en = "Use the desktop view to edit your HUD layout."},
    hud_options = {en = "HUD"},
    hud_size = {en = "HUD size (%%)"},
    hud_size_description = {
        en = "Scale the whole HUD panel. The default value uses the standard VR layout. Applies immediately when the VR HUD is active.",
    },
    hud_distance = {en = "HUD distance (m)"},
    hud_distance_description = {
        en = "Move the HUD nearer or farther while keeping approximately the same apparent size. Applies immediately when the VR HUD is active.",
    },
    hud_internal_scale = {en = "HUD text and icon size (%%)"},
    hud_internal_scale_description = {
        en = "Scale objects inside the HUD without enlarging the panel. Large values may require layout adjustments. Saved item positions are preserved.",
    },
    mod_name = {
        en = "Darktide VR",
    },
    mod_description = {
        en = "Experimental native stereo VR support for Darktide.",
    },
    movement_reference = {
        en = "Movement direction",
    },
    movement_reference_head = {
        en = "Headset-relative",
    },
    movement_reference_left_hand = {
        en = "Left-hand-relative",
    },
}
