return {
    vr_crosshair_scale = {en = "Crosshair scale (%%)"},
    vr_crosshair_scale_description = {en = "Resize the hand-aim crosshair, charge bars and hit feedback together. Updates while playing. 100% restores the original size; the default is 70%."},
    ads_focus = {en = "Aim-down-sights focus"},
    ads_focus_description = {en = "While aiming down sights: a soft vignette at the edges of view, a tighter crosshair and steadier aim. No zoom. Off leaves the view unchanged."},
    vr_aim_stabilization = {en = "Weapon aim stabilisation (%%)"},
    vr_aim_stabilization_description = {en = "Damp small aiming tremors while responding faster to deliberate movement. Higher values steady the aim more. Set to zero to disable. Applies to ranged weapons, including staffs."},
    controller_action_binding_description = {en = "Choose the controller input for this action. Actions can share a control: for example, interact and reload on X. Right-stick left/right actions require turning to be off. Hub overrides apply only in the hub."},
    melee_preview_toggle = {en = "First melee swing preview"},
    melee_preview_toggle_description = {en = "Show or hide the first light attack's direction while holding your melee weapon idle. Starts off each session. This guide does not guarantee a hit."},
    melee_preview_toggle_button = {en = "Toggle preview"},
    scanner_test_keybind = {en = "Device screen check (opens or closes the scanner display on the equipped device)"},
    melee_preview_keybind = {en = "Toggle melee preview shortcut"},
    melee_preview_keybind_description = {en = "Toggle the swing guide without opening chat. Default: F6."},
    vr_gun_pitch = {en = "Gun pitch angle (degrees)"},
    vr_gun_pitch_description = {en = "Tilt guns relative to the controller. Negative angles lower the barrel; positive angles raise it. Updates gun, hand and aim together. Does not affect staffs."},
    remote_mission_input = {en = "VR input and hands in online missions"},
    remote_mission_input_description = {en = "On a mission server you do not host, use the same stock-input route as Psykhanium's online rules: controller buttons and movement, hand-aimed firing through the server's normal firing position, and local hand and weapon presentation. Off keeps online missions view-only. Applies immediately."},
    mode_options = {en = "Hub and missions"},
    spectate_third_person = {en = "Third-person spectating"},
    spectate_third_person_description = {en = "When dead or captured and watching a teammate, follow them with the third-person camera instead of looking through their eyes. Applies on the next mission."},
    hub_third_person = {en = "Third-person body in the hub"},
    hub_third_person_description = {en = "Show the stock third-person character in the hub instead of the first-person body, with the equipped weapons hidden. Combat areas always use first person. Applies on the next hub visit."},
    stereo_cinematics = {en = "In-engine cinematics in stereo"},
    stereo_cinematics_description = {en = "Watch in-engine cutscenes in the world: the cinematic camera moves and turns you, your head adds its own look, and subtitles are shown on the HUD panel. Off shows cutscenes on the flat panel. Cinematic cameras cut and shake; turn this off if that is uncomfortable."},
    psykhanium_online_rules = {en = "Online combat rules in Psykhanium"},
    psykhanium_online_rules_description = {en = "Aim with the right hand using normal firing positions, button melee and movement rules. Room movement stays visual and training aids remain. Applies on your next visit to Psykhanium; online missions are still under development."},
    vr_menu_back = {en = "B"},
    vr_menu_point_select = {en = "Point + RT"},
    vr_menu_point_secondary = {en = "Point + LT"},
    vr_turning = {en = "VR turning"},
    vr_turning_description = {en = "Turn with the right stick horizontally. Centre it after menus, tracking loss or changing modes. Keyboard and mouse controls remain available."},
    vr_turn_mode = {en = "Turning mode"},
    vr_turn_mode_description = {en = "Smooth turning is the default. Snap turns once per stick deflection. Turn this off to use left/right stick shortcuts instead."},
    vr_turn_smooth = {en = "Smooth"},
    vr_turn_snap45 = {en = "Snap 45 degrees"},
    vr_turn_snap90 = {en = "Snap 90 degrees"},
    vr_turn_off = {en = "Off (allow horizontal shortcuts)"},
    vr_turn_speed = {en = "Smooth speed (degrees per second)"},
    vr_turn_speed_description = {en = "Speed at full right-stick deflection. Partial deflection turns more slowly. Only applies to smooth turning."},
    vr_prompt_right_trigger = {en = "RT"},
    vr_prompt_left_trigger = {en = "LT"},
    vr_prompt_right_grip = {en = "R Grip"},
    vr_prompt_left_grip = {en = "L Grip"},
    vr_prompt_x = {en = "X"},
    vr_prompt_y = {en = "Y"},
    vr_prompt_a = {en = "A"},
    vr_prompt_b = {en = "B"},
    vr_prompt_l3 = {en = "L3"},
    vr_prompt_r3 = {en = "R3"},
    vr_prompt_menu = {en = "Menu"},
    vr_prompt_right_stick_up = {en = "RS Up"},
    vr_prompt_right_stick_down = {en = "RS Down"},
    vr_prompt_right_stick_left = {en = "RS Left"},
    vr_prompt_right_stick_right = {en = "RS Right"},
    vr_prompt_switch = {en = "switch"},
    controller_bindings = {en = "Combat controller bindings"},
    controller_hub_bindings = {en = "Hub overrides"},
    controller_hub_bindings_description = {en = "Choose a different control for an action in the hub, or use Same as combat. Release held controls after changing context."},
    vr_action_inherit = {en = "Same as combat"},
    vr_action_inventory = {en = "Open inventory / talents"},
    vr_action_pocketable = {en = "Equip carried item / supply crate"},
    vr_action_stim = {en = "Equip stim"},
    vr_action_device = {en = "Equip scanner / mission device"},
    vr_action_cycle_pocketables = {en = "Cycle carried item / stim"},
    vr_action_inspect_target = {en = "Inspect operative / pet companion"},
    vr_action_tactical_overlay = {en = "Hold tactical overlay"},
    vr_action_communication_wheel = {en = "Hold communication wheel"},
    vr_action_push_to_talk = {en = "Hold push-to-talk"},
    vr_hub_bind_right_trigger = {en = "Hub: right trigger"},
    vr_hub_bind_left_trigger = {en = "Hub: left trigger"},
    vr_hub_bind_right_grip = {en = "Hub: right grip"},
    vr_hub_bind_left_grip = {en = "Hub: left grip"},
    vr_hub_bind_x = {en = "Hub: X"},
    vr_hub_bind_y = {en = "Hub: Y"},
    vr_hub_bind_a = {en = "Hub: A"},
    vr_hub_bind_b = {en = "Hub: B"},
    vr_hub_bind_l3 = {en = "Hub: L3"},
    vr_hub_bind_r3 = {en = "Hub: R3"},
    vr_hub_bind_menu = {en = "Hub: menu button"},
    vr_hub_bind_right_stick_up = {en = "Hub: right stick up"},
    vr_hub_bind_right_stick_down = {en = "Hub: right stick down"},
    vr_hub_bind_right_stick_left = {en = "Hub: right stick left (turning off)"},
    vr_hub_bind_right_stick_right = {en = "Hub: right stick right (turning off)"},
    controller_bindings_description = {en = "Choose a control beside each action. Unbound actions have no controller input. Actions may share a button; saved extra bindings are preserved until you replace them. Release buttons and centre the stick after changes. Menu navigation keeps its standard controls. Reset settings to restore the original layout."},
    vr_bind_right_trigger = {en = "Right trigger"},
    vr_bind_left_trigger = {en = "Left trigger"},
    vr_bind_right_grip = {en = "Right grip"},
    vr_bind_left_grip = {en = "Left grip"},
    vr_bind_x = {en = "X (left primary button)"},
    vr_bind_y = {en = "Y (left secondary button)"},
    vr_bind_a = {en = "A (right primary button)"},
    vr_bind_b = {en = "B (right secondary button)"},
    vr_bind_l3 = {en = "L3 (left stick click)"},
    vr_bind_r3 = {en = "R3 (right stick click)"},
    vr_bind_menu = {en = "Left menu button"},
    vr_bind_right_stick_up = {en = "Right stick up"},
    vr_bind_right_stick_down = {en = "Right stick down"},
    vr_bind_right_stick_left = {en = "Right stick left (turning off)"},
    vr_bind_right_stick_right = {en = "Right stick right (turning off)"},
    vr_action_unbound = {en = "Unbound"},
    vr_action_primary = {en = "Primary attack / fire"},
    vr_action_alternate = {en = "Aim / block / alternate attack"},
    vr_action_special = {en = "Weapon special"},
    vr_action_interact = {en = "Interact"},
    vr_action_reload = {en = "Reload"},
    vr_action_interact_reload = {en = "Interact + reload (original)"},
    vr_action_pocketable_device = {en = "Carried item + scanner (original)"},
    vr_action_quick_wield = {en = "Switch weapon"},
    vr_action_jump = {en = "Jump"},
    vr_action_dodge = {en = "Dodge"},
    vr_action_jump_dodge = {en = "Jump + dodge (original)"},
    vr_action_crouch = {en = "Crouch"},
    vr_action_sprint = {en = "Sprint"},
    vr_action_tag = {en = "Tag target"},
    vr_action_blitz = {en = "Blitz / grenade"},
    vr_action_combat_ability = {en = "Combat ability"},
    vr_action_inspect = {en = "Inspect weapon"},
    vr_action_menu = {en = "Open pause menu"},
    hud_editor = {en = "HUD layout editor"},
    hud_editor_button = {en = "Toggle editor"},
    hud_editor_description = {en = "Requires the separate Custom HUD mod. Select this, then close the menus to edit in the desktop view. Select again before closing to cancel."},
    hud_editor_dependency = {en = "Install and enable Custom HUD to edit the HUD layout."},
    hud_editor_gameplay = {en = "Enter gameplay with the VR HUD enabled before opening its layout editor."},
    hud_editor_close_menu = {en = "Close the menus to toggle HUD layout editing in the desktop view."},
    hud_editor_cancelled = {en = "HUD layout editor request cancelled."},
    hud_editor_notice = {en = "Use the desktop view to edit your HUD layout."},
    hud_focus_notice = {en = "Game window not focused: click the Darktide window on the desktop (frame generation and controls pause)."},
    focus_warning = {en = "Warn when the game window loses focus"},
    focus_warning_description = {en = "Show a notice on the VR HUD while another window has the desktop focus. Frame generation and controller input stop until the Darktide window is focused again."},
    hud_options = {en = "HUD"},
    hud_size = {en = "HUD size (%%)"},
    hud_size_description = {
        en = "Scale the whole HUD panel. The default value uses the standard VR layout. Applies immediately when the VR HUD is active.",
    },
    hud_distance = {en = "HUD distance (m)"},
    hud_distance_description = {
        en = "Move the HUD nearer or farther while keeping approximately the same apparent size. Applies immediately when the VR HUD is active.",
    },
    hud_internal_scale = {en = "HUD text and icon size (%%)"},
    hud_internal_scale_description = {
        en = "Scale objects inside the HUD without enlarging the panel. Large values may require layout adjustments. Saved item positions are preserved.",
    },
    mod_name = {
        en = "Darktide VR",
    },
    mod_description = {
        en = "Experimental native stereo VR support for Darktide.",
    },
    movement_reference = {
        en = "Movement direction",
    },
    movement_reference_head = {
        en = "Headset-relative",
    },
    movement_reference_left_hand = {
        en = "Left-hand-relative",
    },
}
